
### CONFIGURATION VALUES for the sensors-anomaly-detection main job

# Elascticsearch cluster config
job.enableElastic: false
elastic.cluster.address: 127.0.0.1
elastic.cluster.port: 9300
elastic.cluster.name: elasticsearch
elastic.bulk.flush.max.actions: 1
elastic.bulk.flush.backoff.enable: true
elastic.bulk.flush.backoff.retries: 3

# Grafana visualizations are not mandatory, but if it is wanted, InfluxDB must be in place too
job.enableGrafana: false

# Flink windowing configuration
flink.window.elements: 100
flink.window.slide: 1

# Default values to connect to InfluxDB
influxdb.url: http://localhost:8086
influxdb.username: admin
influxdb.password: admin
influxdb.dbname: intellisense
